#!/usr/bin/env bash

IFACE=wlan0
read MAC </sys/class/net/$IFACE/address

IP=$(ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')

read USERNAME < /etc/pifinder_username

curl --data "username=${USERNAME}&mac=${MAC}&ip=${IP}" http://pifinder.eee.nottingham.ac.uk/submit.php
