#!/usr/bin/env bash

read -s -p "Enter UoN password: " PWPLAIN

exec 3<<<${PWPLAIN}
PW=$(tr -d '\n' <&3 | iconv -t utf16le | openssl md4 | sed 's/(stdin)= //')
exec 3<&-
unset PWPLAIN
sed -i "s/.*password=.*/  password=hash:$PW/" /etc/wpa_supplicant/wpa_supplicant.conf
unset PW
echo
